version: '3.9'
services:
  redis:
    container_name: cqrs-es-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  nats:
    container_name: cqrs-es-nats
    image: nats:latest
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"

  postgres:
    container_name: cqrs-es-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: es
    ports:
      - "5432:5432"

  adminer:
    container_name: cqrs-es-adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
